// Generated by CoffeeScript 1.7.1
(function() {
  var app;

  app = angular.module('app', ['ngRoute']);

  app.controller('DemoCtrl', [
    '$scope', 'demoService', function($scope, demoService) {
      var Id;
      $scope.hideRows = false;
      $scope.hideRow = function() {
        return $scope.hideRows = !$scope.hideRows;
      };
      $scope.alerts = "loading";
      demoService.getAlerts().then(function(ret) {
        return $scope.alerts = ret;
      });
      $scope.closeAlert = function(index) {
        return $scope.alerts.splice(index, 1);
      };
      $scope.myalert = Id = 0;
      $scope.type = "";
      return $scope.$watch('myalert.Id', function(val) {
        if (val === 1) {
          return $scope.type = "alert-info";
        } else if (val === 2) {
          return $scope.type = "alert-warning";
        } else if (val === 3) {
          return $scope.type = "alert-danger";
        }
      });
    }
  ]);

}).call(this);
