// Generated by CoffeeScript 1.7.1
(function() {
  angular.module('app').config([
    'BASE_WEB_URL', '$routeProvider', '$locationProvider', function(BASE_WEB_URL, $routeProvider, $locationProvider) {
      $locationProvider.html5Mode(true);
      return $routeProvider.when('/home', {
        templateUrl: "" + BASE_WEB_URL + "/Scripts/angular/alert/alert.html",
        controller: 'DemoCtrl'
      }).otherwise({
        redirectTo: '/home'
      });
    }
  ]);

}).call(this);
